In [142]:
import qn
import pandas as pd
from importlib.machinery import SourceFileLoader
import numpy as np

In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
# import sys
# sys.path.insert(0, '.')

In [164]:
import muldataframe as md
MulSeries = md.MulSeries

In [165]:
index = pd.DataFrame([[1,2],[3,5],[3,6]],
                     index=['a','b','b'],
                     columns=['x','y'])
name = pd.Series(['a','b'],index=['e','f'],name='cc')
ms = MulSeries([1,2,3],index=index,name=name)

In [166]:
ms.groupby('x',keep_primary=True,agg_mode='array').mean()

ss:
0    1.0
1    2.5
Name: cc, dtype: float64

index:
  primary_index  x       y
0             a  1       2
1             b  3  [5, 6]

name:
Series([], Name: cc, dtype: object)

In [150]:
ms.groupby(agg_mode='array').mean()

ss:
0    1.0
1    2.5
Name: cc, dtype: float64

index:
  primary_index  x       y
0             a  1       2
1             b  3  [5, 6]

name:
Series([], Name: cc, dtype: object)

In [126]:
df = pd.DataFrame([[1,2,3],[4,2,3],[7,8,9]],columns=['a','b','index'])

In [98]:
type(df.groupby(['b']).mean())

pandas.core.frame.DataFrame

In [127]:
df.reset_index()

   level_0  a  b  index
0        0  1  2      3
1        1  4  2      3
2        2  7  8      9

In [100]:
x = df.groupby(['b','c']).mean()

In [107]:
df.groupby(df.index).mean()

     a    b    c
0  1.0  2.0  3.0
1  4.0  2.0  3.0
2  7.0  8.0  9.0

In [86]:
ms.groupby('x').groupBy.indices

{1: array([0]), 3: array([1, 2])}

ss:
0    1.0
1    2.0
2    3.0
Name: cc, dtype: float64

index:
   x  y
0  1  2
1  3  5
2  3  6

name:
e    a
f    b
Name: cc, dtype: object

In [41]:
list(ms.groupby('x'))

[(1,
  ss:
  a    1
  Name: cc, dtype: int64

  index:
     x  y
  a  1  2

  name:
  Series([], Name: cc, dtype: object)),
 (3,
  ss:
  b    2
  b    3
  Name: cc, dtype: int64

  index:
     x  y
  b  3  4
  b  3  6

  name:
  Series([], Name: cc, dtype: object))]

In [24]:
[x for x in ms.groupby('x')]

TypeError: 'type' object is not iterable

In [47]:
index.loc[:,[True,False]]

   x
a  1
b  3
c  5

In [15]:
ms.__ss__

In [97]:
ms.__div__

<bound method MulSeries.__div__ of ss:
a    1
b    2
c    3
Name: cc, dtype: int64

index:
   x  y
a  1  2
b  3  4
c  5  6

name:
e    a
f    b
Name: cc, dtype: object>

In [92]:
ms.__

In [50]:
ms.call(np.sum)

6

In [48]:
ms.call(np.add,1).call(np.log2)

ss:
a    1.000000
b    1.584963
c    2.000000
Name: cc, dtype: float64

index:
   x  y
a  1  2
b  3  4
c  5  6

name:
e    a
f    b
Name: cc, dtype: object

In [14]:
ms.ss.values

array([1, 2, 3])

In [17]:
np.log2(ms)

ValueError: invalid __array_struct__

In [94]:
ms.mloc[{'a':['c','d']}]

{'a': ['c', 'd']}

In [110]:
ms.index.index.shape

(3,)

In [95]:
ms.mloc[:]

slice(None, None, None)

In [216]:
ms.index.index

Index(['a', 'b', 'c'], dtype='object')

In [160]:
ms.values

array([1, 2, 3])

In [166]:
ms.mname

e    a
f    b
Name: cc, dtype: object

In [183]:
ms.ss.iloc

In [217]:
ms.index.index = [5,6,7]

In [35]:
cc = pd.Series([])

In [37]:
cc.name

In [38]:
x = pd.Series([1,2,3],index=['a','b','c'],name='x')
y = pd.Series([4,5,6],index=['b','b','c'],name='y')

In [39]:
(x+y)

a    NaN
b    6.0
b    7.0
c    9.0
dtype: float64

In [34]:
y.name

'y'

In [24]:
z = pd.Series(5)

In [25]:
z

0    5
dtype: int64

In [234]:
x.keys()

dict_keys(['z', 'd'])

In [57]:
pd.Series([1,2,3]).iloc[slice(None)]

0    1
1    2
2    3
dtype: int64

In [58]:
slice(None)

slice(None, None, None)

In [85]:
x = (5,)

In [86]:
x

(5,)

In [82]:
list(enumerate(x))

[(0, 5)]

In [51]:
x = pd.Series([1,2,3])
y = np.log2(x)

In [54]:
x % 2

0    1
1    0
2    1
dtype: int64

In [107]:
class A:
    def __init__(self):
        self.__abc = 10
        self._bc = 5

In [108]:
a = A()
print(a._bc)
print(a.__abc)

5

AttributeError: 'A' object has no attribute '__abc'

In [115]:
kk = pd.DataFrame([[],[],[]],index=[1,2,3])

In [40]:
class abc():
    def __init__(self,a):
        self.a = a
    def __iter__(self):
        for i in range(3):
            yield i
    # def __array__(self):
    #     return np.array([self.a])

In [42]:
x = abc(5)

In [44]:
for i in x:
    print(i)

0
1
2

In [20]:
x = abc([1,2,3])
y = np.log2(x)

In [22]:
def test(func):
    print(func)
test(+)

SyntaxError: invalid syntax (1679959165.py, line 3)

In [54]:
x = pd.Series([1,2],name='a')
y = pd.Series([3,4],name='b')
pd.concat([x,y])

0    1
1    2
0    3
1    4
dtype: int64

In [58]:
x = pd.DataFrame([[1,2,3]],columns=['a','b','c'])
y = pd.DataFrame([[1,3]],columns=['c','a'])
pd.concat([x,y],join='inner')

   a    b  c
0  1  2.0  3
0  3  NaN  1

In [59]:
getattr(np,'sum')