In [1]:
import qn
qn.config(globals())

In [2]:
%load_ext autoreload
%autoreload 2

In [6]:
import numpy as np
import muldataframe as md
MulDataFrame = md.MulDataFrame

In [16]:
index = pd.DataFrame([[1,2],[3,6],[5,6]],
                     index=['a','b','b'],
                     columns=['x','y'])
columns = pd.DataFrame([[5,7],[3,6]],
                     index=['c','d'],
                     columns=['f','g'])
md = MulDataFrame([[1,2],[8,9],[8,10]],index=index,
                  columns=columns)

In [34]:
md.df.mean(axis=1)

a    1.5
b    8.5
b    9.0
dtype: float64

In [40]:
pd.DataFrame(md.df.iloc[:2])

   c  d
a  1  2
b  8  9

In [38]:
md.__df = [1,2]
md.__df

[1, 2]

In [33]:
md * pd.Series([2,2],index=['d','c'])

df:
    c   d
a   2   4
b  16  18
b  16  20

index:
   x  y
a  1  2
b  3  6
b  5  6

columns:
   f  g
c  5  7
d  3  6

In [30]:
md + pd.DataFrame([[1,1],[1,1],[1,1]],index=['a','b','b'],
                  columns=['c','d'])

NotImplementedError:

In [20]:
md

df:
   c   d
a  1   2
b  8   9
b  8  10

index:
   x  y
a  1  2
b  3  6
b  5  6

columns:
   f  g
c  5  7
d  3  6

In [14]:
import inspect
hasattr(np.mean,'__call__')

# type(np.mean) == types.MethodType

True

In [5]:
md.iloc[:,0]

ss:
a    1
b    8
b    8
Name: c, dtype: int64

index:
   x  y
a  1  2
b  3  6
b  5  6

name:
f    5
g    7
Name: c, dtype: int64

In [43]:
len(md.df.iloc[0])

2

In [8]:
df = md.df

In [28]:
df.index.name = 'xx'

In [29]:
lf = df.melt(value_vars=['c','d'],ignore_index=False)

In [31]:
lf

   variable  value
xx
a         c      1
b         c      8
b         c      8
a         d      2
b         d      9
b         d     10

In [33]:
x = True
x is True

True

In [39]:
x = 5
hasattr(md,'__pandas_priority__')

True

In [35]:
x = np.array([[1,2],[3,4],[5,6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [14]:
def abc(x=None,y=None,**kwargs):
    print(x,y,kwargs)

In [18]:
abc(5,c=3)

5 None {'c': 3}

In [12]:
df.query('index == "b"')

   c   d
b  8   9
b  8  10

In [6]:
md.set_index('c',drop=True)

df:
    d
a   2
b   9
b  10

index:
   x  y  c
a  1  2  1
b  3  6  8
b  5  6  8

columns:
   f  g
d  3  6

In [72]:
df = md.df

In [49]:
df.drop_duplicates('c')

   c  d
a  1  2
b  8  9

In [26]:
md.drop_duplicates(['c'])

df:
   c  d
a  1  2
b  8  9

index:
   x  y
a  1  2
b  3  6

columns:
   f  g
c  5  7
d  3  6

In [24]:
md.loc['b']

df:
   c   d
b  8   9
b  8  10

index:
   x  y
b  3  6
b  5  6

columns:
   f  g
c  5  7
d  3  6

In [56]:
class A():
    def __init__(self, x):
        self.x = x
        
    def f(self):
        print(self.x)

class B(A):
    def __init__(self, x):
        super().__init__(x)
    def f(self):
        print(self.x*2)

In [92]:
x = pd.Series([1,2,2])
x.loc[~x.duplicated()]

0    1
1    2
dtype: int64

In [96]:
df.values[[False,True,False]]

array([[8, 9]])

In [28]:
x = pd.Series([1,2,3],index=['a','b','b'])

In [30]:
x.shape

1

In [115]:
pd.concat([df,x],axis=1)

   c   d  0
a  1   2  1
b  8   9  2
b  8  10  3

In [91]:
x.duplicated()

0    False
1    False
2     True
dtype: bool

In [66]:
b = B(3)
b.f()
super(B,b).f()

6
3

In [12]:
class LittleMeta(type):
    def __new__(cls, clsname, superclasses, attributedict):
        print("clsname: ", clsname)
        print("superclasses: ", superclasses)
        print("attributedict: ", attributedict)
        return type.__new__(cls, clsname, superclasses, attributedict)
    def __init__(cls, clsname, superclasses, attributedict):
        print("init clsname: ", clsname)
        print("init superclasses: ", superclasses)
        print("init attributedict: ", attributedict)
        return type.__init__(cls, clsname, superclasses, attributedict)
    def abc(self):
        return "abc"

In [15]:
from abc import ABC,abstractmethod

class A(ABC):
    def __init__(self, x):
        self.x = x
    
    @classmethod
    def f(self):
        return self.x + 1
    
    @abstractmethod
    def f2(self):
        return self.x + 1
    
    def f3(self):
        return self.x + 1

In [16]:
k = A(5)

TypeError: Can't instantiate abstract class A with abstract method f2

In [5]:
dict(A.__dict__)

{'__module__': '__main__',
 '__init__': <function __main__.A.__init__(self, x)>,
 'f': <classmethod(<function A.f at 0x16aee9c60>)>,
 'f2': <function __main__.A.f2(self)>,
 'f3': <function __main__.A.f3(self)>,
 '__dict__': <attribute '__dict__' of 'A' objects>,
 '__weakref__': <attribute '__weakref__' of 'A' objects>,
 '__doc__': None,
 '__abstractmethods__': frozenset({'f2'}),
 '_abc_impl': <_abc._abc_data at 0x16aefbdc0>}

In [18]:
abc = type('abc',(ABC,),dict(A.__dict__))

In [19]:
abc(5)

TypeError: Can't instantiate abstract class abc with abstract method f2

In [21]:
class A(pd.DataFrame,metaclass=LittleMeta):
    def f(self):
        print('a')

clsname:  A
superclasses:  (<class 'pandas.core.frame.DataFrame'>,)
attributedict:  {'__module__': '__main__', '__qualname__': 'A', 'f': <function A.f at 0x16b63ae80>}
init clsname:  A
init superclasses:  (<class 'pandas.core.frame.DataFrame'>,)
init attributedict:  {'__module__': '__main__', '__qualname__': 'A', 'f': <function A.f at 0x16b63ae80>}

In [20]:
class A:
    pass

In [9]:
index = pd.DataFrame([[1,2],[3,6],[5,6]],
                     index=['a','b','b'],
                     columns=['x','y'])
df =pd.DataFrame([[1,2],[8,9],[8,10]],index=pd.MultiIndex.from_frame(index))

In [11]:
for k, row in df.iterrows():
    print(k,row)

(1, 2) 0    1
1    2
Name: (1, 2), dtype: int64
(3, 6) 0    8
1    9
Name: (3, 6), dtype: int64
(5, 6) 0     8
1    10
Name: (5, 6), dtype: int64

In [17]:
xf = pd.DataFrame([[1,2],[3,4],[5,6]],index=['a','b','b'])

In [18]:
xf.groupby()

TypeError: You have to supply one of 'by' and 'level'

In [14]:
row

0     8
1    10
Name: (5, 6), dtype: int64

In [19]:
def fa():
    pass
fa.__name__

'fa'

In [14]:
df = md.df
df.index = pd.MultiIndex.from_frame(index)
df.columns = pd.MultiIndex.from_frame(columns)

In [22]:
df

f    5   3
g    7   6
x y
1 2  1   2
3 6  8   9
5 6  8  10

In [29]:
df.index.to_frame(index=False)

   x  y
0  1  2
1  3  6
2  5  6

In [30]:
vals = df.values
vals[0,0]

1

In [40]:
df

[autoreload of muldataframe.util failed: Traceback (most recent call last):
  File "/Users/qn/miniforge3/lib/python3.11/site-packages/IPython/extensions/autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "/Users/qn/miniforge3/lib/python3.11/site-packages/IPython/extensions/autoreload.py", line 475, in superreload
    module = reload(module)
             ^^^^^^^^^^^^^^
  File "/Users/qn/miniforge3/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/qn/Documents/NuMedii_mac/Jandas/muldataframe/muldataframe/util.py", line 47
    pass
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 45
]

    c   d
xx
a   1   2
b   8   9
b   8  10

In [37]:
x = md.__class__.__name__

In [39]:
md.xx