In [1]:
import qn
qn.config(globals())

In [2]:
%load_ext autoreload
%autoreload 2

In [4]:
import muldataframe as md
MulDataFrame = md.MulDataFrame

In [5]:
index = pd.DataFrame([[1,2],[3,6],[5,6]],
                     index=['a','b','b'],
                     columns=['x','y'])
columns = pd.DataFrame([[5,7],[3,6]],
                     index=['c','d'],
                     columns=['f','g'])
md = MulDataFrame([[1,2],[8,9],[8,10]],index=index,
                  columns=columns)

In [6]:
md.set_index('c',drop=True)

df:
    d
a   2
b   9
b  10

index:
   x  y  c
a  1  2  1
b  3  6  8
b  5  6  8

columns:
   f  g
d  3  6

In [72]:
df = md.df

In [49]:
df.drop_duplicates('c')

   c  d
a  1  2
b  8  9

In [26]:
md.drop_duplicates(['c'])

df:
   c  d
a  1  2
b  8  9

index:
   x  y
a  1  2
b  3  6

columns:
   f  g
c  5  7
d  3  6

In [24]:
md.loc['b']

df:
   c   d
b  8   9
b  8  10

index:
   x  y
b  3  6
b  5  6

columns:
   f  g
c  5  7
d  3  6

In [56]:
class A():
    def __init__(self, x):
        self.x = x
        
    def f(self):
        print(self.x)

class B(A):
    def __init__(self, x):
        super().__init__(x)
    def f(self):
        print(self.x*2)

In [92]:
x = pd.Series([1,2,2])
x.loc[~x.duplicated()]

0    1
1    2
dtype: int64

In [96]:
df.values[[False,True,False]]

array([[8, 9]])

In [28]:
x = pd.Series([1,2,3],index=['a','b','b'])

In [30]:
x.shape

1

In [115]:
pd.concat([df,x],axis=1)

   c   d  0
a  1   2  1
b  8   9  2
b  8  10  3

In [91]:
x.duplicated()

0    False
1    False
2     True
dtype: bool

In [66]:
b = B(3)
b.f()
super(B,b).f()

6
3

In [12]:
class LittleMeta(type):
    def __new__(cls, clsname, superclasses, attributedict):
        print("clsname: ", clsname)
        print("superclasses: ", superclasses)
        print("attributedict: ", attributedict)
        return type.__new__(cls, clsname, superclasses, attributedict)
    def __init__(cls, clsname, superclasses, attributedict):
        print("init clsname: ", clsname)
        print("init superclasses: ", superclasses)
        print("init attributedict: ", attributedict)
        return type.__init__(cls, clsname, superclasses, attributedict)
    def abc(self):
        return "abc"

In [15]:
from abc import ABC,abstractmethod

class A(ABC):
    def __init__(self, x):
        self.x = x
    
    @classmethod
    def f(self):
        return self.x + 1
    
    @abstractmethod
    def f2(self):
        return self.x + 1
    
    def f3(self):
        return self.x + 1

In [16]:
k = A(5)

TypeError: Can't instantiate abstract class A with abstract method f2

In [5]:
dict(A.__dict__)

{'__module__': '__main__',
 '__init__': <function __main__.A.__init__(self, x)>,
 'f': <classmethod(<function A.f at 0x16aee9c60>)>,
 'f2': <function __main__.A.f2(self)>,
 'f3': <function __main__.A.f3(self)>,
 '__dict__': <attribute '__dict__' of 'A' objects>,
 '__weakref__': <attribute '__weakref__' of 'A' objects>,
 '__doc__': None,
 '__abstractmethods__': frozenset({'f2'}),
 '_abc_impl': <_abc._abc_data at 0x16aefbdc0>}

In [18]:
abc = type('abc',(ABC,),dict(A.__dict__))

In [19]:
abc(5)

TypeError: Can't instantiate abstract class abc with abstract method f2

In [21]:
class A(pd.DataFrame,metaclass=LittleMeta):
    def f(self):
        print('a')

clsname:  A
superclasses:  (<class 'pandas.core.frame.DataFrame'>,)
attributedict:  {'__module__': '__main__', '__qualname__': 'A', 'f': <function A.f at 0x16b63ae80>}
init clsname:  A
init superclasses:  (<class 'pandas.core.frame.DataFrame'>,)
init attributedict:  {'__module__': '__main__', '__qualname__': 'A', 'f': <function A.f at 0x16b63ae80>}

In [20]:
class A:
    pass

In [9]:
index = pd.DataFrame([[1,2],[3,6],[5,6]],
                     index=['a','b','b'],
                     columns=['x','y'])
df =pd.DataFrame([[1,2],[8,9],[8,10]],index=pd.MultiIndex.from_frame(index))

In [11]:
for k, row in df.iterrows():
    print(k,row)

(1, 2) 0    1
1    2
Name: (1, 2), dtype: int64
(3, 6) 0    8
1    9
Name: (3, 6), dtype: int64
(5, 6) 0     8
1    10
Name: (5, 6), dtype: int64

In [17]:
xf = pd.DataFrame([[1,2],[3,4],[5,6]],index=['a','b','b'])

In [18]:
xf.groupby()

TypeError: You have to supply one of 'by' and 'level'

In [14]:
row

0     8
1    10
Name: (5, 6), dtype: int64

In [19]:
def fa():
    pass
fa.__name__

'fa'

In [25]:
df.mean(axis=1)

x  y
1  2    1.5
3  6    8.5
5  6    9.0
dtype: float64

In [24]:
df

     0   1
x y
1 2  1   2
3 6  8   9
5 6  8  10